version: '3.8'

services:
  web:
    image: evelonk/cloudlab:checkcorrect
    build:
      context: ./backend
    container_name: taski_backend
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
  
volumes:
  sqlite_data: